"""add scoring and pool enhancement tables

Revision ID: 5653af0ec7a7
Revises: 320070266d6c
Create Date: 2026-06-01 17:28:18.836380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5653af0ec7a7'
down_revision: Union[str, Sequence[str], None] = '320070266d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Template name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Template description'),
    sa.Column('weights', sa.JSON(), nullable=False, comment='Dimension weights as JSON'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='Whether this is the default template'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score_template_default', 'score_template', ['is_default'], unique=False)
    op.create_table('etf_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('etf_code', sa.String(length=20), nullable=False, comment='ETF code'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='Trade date'),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='Score template ID'),
    sa.Column('composite_score', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Composite score'),
    sa.Column('score_return', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Return dimension score'),
    sa.Column('score_risk', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Risk dimension score'),
    sa.Column('score_sharpe', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Sharpe dimension score'),
    sa.Column('score_liquidity', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Liquidity dimension score'),
    sa.Column('score_trend', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='Trend dimension score'),
    sa.Column('rank_overall', sa.Integer(), nullable=True, comment='Overall rank across all ETFs'),
    sa.Column('rank_category', sa.Integer(), nullable=True, comment='Rank within category'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['etf_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['score_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_code', 'trade_date', 'template_id', name='uq_etf_score_code_date_template')
    )
    op.create_index('idx_etf_score_composite', 'etf_score', ['composite_score'], unique=False)
    op.create_index('idx_etf_score_date', 'etf_score', ['trade_date'], unique=False)
    op.create_index('idx_etf_score_template', 'etf_score', ['template_id'], unique=False)
    op.create_table('pool_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pool_id', sa.Integer(), nullable=False, comment='Pool ID'),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='Snapshot date'),
    sa.Column('data', sa.JSON(), nullable=False, comment='Snapshot data as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['pool_id'], ['etf_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'snapshot_date', name='uq_pool_snapshot_pool_date')
    )
    op.create_index('idx_pool_snapshot_pool_date', 'pool_snapshot', ['pool_id', 'snapshot_date'], unique=False)
    op.create_table('pool_weight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pool_id', sa.Integer(), nullable=False, comment='Pool ID'),
    sa.Column('etf_code', sa.String(length=20), nullable=False, comment='ETF code'),
    sa.Column('target_weight', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Target weight percentage (e.g. 25.00 = 25%)'),
    sa.Column('suggested_weight', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Suggested weight percentage from algorithm'),
    sa.Column('weight_source', sa.String(length=20), nullable=False, comment='Weight source: manual/equal/score/risk_parity'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.ForeignKeyConstraint(['etf_code'], ['etf_info.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['etf_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'etf_code', name='uq_pool_weight_pool_etf')
    )
    op.create_table('report_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('report_type', sa.String(length=50), nullable=False, comment='Report type (e.g. daily, weekly, monthly)'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='Report date'),
    sa.Column('pool_id', sa.Integer(), nullable=True, comment='ETF pool ID'),
    sa.Column('template_id', sa.Integer(), nullable=True, comment='Score template ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending/running/success/failed'),
    sa.Column('format', sa.String(length=20), nullable=True, comment='Output format (e.g. pdf, html, xlsx)'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Generated file path'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Generation start time'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Generation finish time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.ForeignKeyConstraint(['pool_id'], ['etf_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['score_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_metadata_date', 'report_metadata', ['report_date'], unique=False)
    op.create_index('idx_report_metadata_status', 'report_metadata', ['status'], unique=False)
    op.create_index('idx_report_metadata_type', 'report_metadata', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_report_metadata_type', table_name='report_metadata')
    op.drop_index('idx_report_metadata_status', table_name='report_metadata')
    op.drop_index('idx_report_metadata_date', table_name='report_metadata')
    op.drop_table('report_metadata')
    op.drop_table('pool_weight')
    op.drop_index('idx_pool_snapshot_pool_date', table_name='pool_snapshot')
    op.drop_table('pool_snapshot')
    op.drop_index('idx_etf_score_template', table_name='etf_score')
    op.drop_index('idx_etf_score_date', table_name='etf_score')
    op.drop_index('idx_etf_score_composite', table_name='etf_score')
    op.drop_table('etf_score')
    op.drop_index('idx_score_template_default', table_name='score_template')
    op.drop_table('score_template')
    # ### end Alembic commands ###
